// packages/tiptap/src/components/BlockEditor/BlockEditor.tsx
import { EditorContent } from '@tiptap/react'
import { useRef } from 'react'

import { LinkMenu } from '@/components/menus'

import { useBlockEditor } from '@/hooks/useBlockEditor'

import '@/styles/index.css'
import '@/styles/globals.css'

import ImageBlockMenu from '@/extensions/ImageBlock/components/ImageBlockMenu'
import { ColumnsMenu } from '@/extensions/MultiColumn/menus'
import { TableColumnMenu, TableRowMenu } from '@/extensions/Table/menus'
import * as Y from 'yjs'
import { TextMenu } from '../menus/TextMenu'

export const BlockEditor = ({ ydoc }: { ydoc?: Y.Doc }) => {
  const menuContainerRef = useRef(null)

  const { editor, users } = useBlockEditor({ ydoc })

  if (!editor || !users) {
    return null
  }

  return (
    <div className="relative flex flex-col flex-1 h-full overflow-hidden">
      <EditorContent editor={editor} className="flex-1 overflow-y-auto" />
      <LinkMenu editor={editor} appendTo={menuContainerRef} />
      <TextMenu editor={editor} />
      <ColumnsMenu editor={editor} appendTo={menuContainerRef} />
      <TableRowMenu editor={editor} appendTo={menuContainerRef} />
      <TableColumnMenu editor={editor} appendTo={menuContainerRef} />
      <ImageBlockMenu editor={editor} appendTo={menuContainerRef} />
    </div>
  )
}

export default BlockEditor

// packages/vue/src/components/editor/components/block-editor/index.tsx
import { EditorContent } from '@tiptap/vue-3'
import { defineComponent } from 'vue'

import { ColumnsMenu } from '../menus/columns-menu'
import { ContentItemMenu } from '../menus/content-item-menu'
import { ImageBlockMenu } from '../menus/image-block-menu'
import { LinkMenu } from '../menus/link-menu'
import { TableColumnMenu, TableRowMenu } from '../menus/table-menu'
import { TextMenu } from '../menus/text-menu'
import { EditorToolbar } from '../toolbar'

import type { Editor } from '@tiptap/core'

export const BlockEditor = defineComponent({
  name: 'BlockEditor',
  props: {
    editor: {
      type: Object as () => Editor | null,
      required: true,
    },
    isReady: {
      type: Boolean,
      default: true,
    },
  },
  setup(props) {
    if (!props.isReady || !props.editor) {
      return () => (
        <div class="flex h-full items-center justify-center">
          Loading editor...
        </div>
      )
    }

    return () => (
      <div class="flex h-full">
        <div class="relative flex flex-col flex-1 h-full overflow-hidden">
          <EditorToolbar editor={props.editor} />
          <div class="flex-1 overflow-auto">
            <EditorContent editor={props.editor} />
            <ContentItemMenu editor={props.editor} />
            <LinkMenu editor={props.editor} />
            <TextMenu editor={props.editor} />
            <ColumnsMenu editor={props.editor} />
            <TableRowMenu editor={props.editor} />
            <TableColumnMenu editor={props.editor} />
            <ImageBlockMenu editor={props.editor} />
          </div>
        </div>
      </div>
    )
  },
})
