// packages/core/src/components/editor/components/BlockEditor/BlockEditor.tsx
import { EditorContent } from '@tiptap/react'
import { useRef } from 'react'

import { ContentItemMenu } from '../menus/ContentItemMenu'
import { LinkMenu } from '../menus/LinkMenu'
import { TextMenu } from '../menus/TextMenu'
import { EditorToolbar } from '../Toolbar'

import type { Editor } from '@tiptap/react'

import '@/styles/index.css'

import { Sidebar } from '@/components/editor/components/Sidebar'
import { ImageBlockMenu } from '@/components/editor/extensions/ImageBlock/components/ImageBlockMenu'
import { ColumnsMenu } from '@/components/editor/extensions/MultiColumn/menus'
import {
  TableColumnMenu,
  TableRowMenu,
} from '@/components/editor/extensions/Table/menus'
import { useSidebar } from '@/hooks/use-sidebar'

export const BlockEditor = ({
  editor,
  isReady = true,
}: {
  editor: Editor | null
  isReady?: boolean
}) => {
  const menuContainerRef = useRef(null)
  const leftSidebar = useSidebar()

  if (!isReady || !editor) {
    return (
      <div className="flex h-full items-center justify-center">
        Loading editor...
      </div>
    )
  }

  return (
    <div className="flex h-full" ref={menuContainerRef}>
      <Sidebar
        isOpen={leftSidebar.isOpen}
        onClose={leftSidebar.close}
        editor={editor}
      />
      <div className="relative flex flex-col flex-1 h-full overflow-hidden">
        <EditorToolbar editor={editor} />
        <div className="flex-1 w-full overflow-y-auto p-4">
          <EditorContent editor={editor} className="h-full w-full" />
          <ContentItemMenu editor={editor} />
          <LinkMenu editor={editor} appendTo={menuContainerRef} />
          <TextMenu editor={editor} />
          <ColumnsMenu editor={editor} appendTo={menuContainerRef} />
          <TableRowMenu editor={editor} appendTo={menuContainerRef} />
          <TableColumnMenu editor={editor} appendTo={menuContainerRef} />
          <ImageBlockMenu editor={editor} appendTo={menuContainerRef} />
        </div>
      </div>
    </div>
  )
}

export default BlockEditor

// packages/vue/src/components/editor/components/block-editor/index.tsx
import { EditorContent } from '@tiptap/vue-3'
import { defineComponent } from 'vue'

import { ColumnsMenu } from '../menus/columns-menu'
import { ContentItemMenu } from '../menus/content-item-menu'
import { ImageBlockMenu } from '../menus/image-block-menu'
import { LinkMenu } from '../menus/link-menu'
import { TableColumnMenu, TableRowMenu } from '../menus/table-menu'
import { TextMenu } from '../menus/text-menu'
import { EditorToolbar } from '../toolbar'

import type { Editor } from '@tiptap/core'

export const BlockEditor = defineComponent({
  name: 'BlockEditor',
  props: {
    editor: {
      type: Object as () => Editor | null,
      required: true,
    },
    isReady: {
      type: Boolean,
      default: true,
    },
  },
  setup(props) {
    if (!props.isReady || !props.editor) {
      return () => (
        <div class="flex h-full items-center justify-center">
          Loading editor...
        </div>
      )
    }

    return () => (
      <div class="flex h-full">
        <div class="relative flex flex-col flex-1 h-full overflow-hidden">
          <EditorToolbar editor={props.editor} />
          <div class="flex-1 overflow-auto">
            <EditorContent editor={props.editor} />
            <ContentItemMenu editor={props.editor} />
            <LinkMenu editor={props.editor} />
            <TextMenu editor={props.editor} />
            <ColumnsMenu editor={props.editor} />
            <TableRowMenu editor={props.editor} />
            <TableColumnMenu editor={props.editor} />
            <ImageBlockMenu editor={props.editor} />
          </div>
        </div>
      </div>
    )
  },
})
